services:
  mariadb:
    image: mariadb:11.1.2
    restart: unless-stopped
    volumes:
      - ./infra/volumes/dev/database:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
        - app-network

  vulnerable-symfony-php:
    build:
      context: ./infra/dev/vulnerable/symfony-php
    volumes:
      - ./infra/volumes/dev/composer:/root/.composer
      - ./infra/dev/vulnerable/symfony-php/project.ini:/usr/local/etc/php/conf.d/project.ini:ro
      - ./vulnerable/app:/var/www/app
    environment:
      APP_ENV: dev
    depends_on:
      - mariadb
    tty: true
    networks:
      - app-network
    command: /bin/sh -c "chown -R www-data:www-data /var/www/app && php-fpm"  # Changer les permissions puis d√©marrer PHP-FPM


  vulnerable-symfony-nginx:
    image: nginx:latest
    volumes:
      - ./infra/volumes/dev/logs/nginx:/var/log/nginx
      - ./infra/dev/vulnerable/symfony-nginx/virtualhost.conf:/etc/nginx/conf.d/default.conf:ro
      - ./vulnerable/app:/var/www/app
    ports:
      - "801:80"
    depends_on:
      - vulnerable-symfony-php
    tty: true
    networks:
      - app-network

  mailcatcher:
    restart: on-failure
    image: schickling/mailcatcher
    ports: [ 1025, 1080:1080 ]
    networks:
      - app-network

networks:
  app-network:
    driver: bridge